# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - ps: npm test
  - cmd: npm test

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/3d5ed28fa9ae4c25f46f
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
