# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2015

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Users\appveyor\AppData\Local\Temp\chocolatey -> appveyor.yml

# what combinations to test
environment:
  global:
    ELECTRON_NO_ATTACH_CONSOLE: true
    nodejs_version: 6.1.0
  matrix:
    - TARGET_ARCH: x64
    - TARGET_ARCH: x86

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@4.4.4
  - npm install -g rimraf asar
  - choco install nsis -version 2.51
  - choco install jq
  - choco install curl
  - set PATH=C:\Program Files (x86)\Windows Kits\8.1\bin\x86;%PATH%
  - set PATH=C:\Program Files (x86)\NSIS;%PATH%
  - set PATH=C:\MinGW\bin;%PATH%
  - set PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - pip install codespell==1.9.2 awscli
  - make info
  - make electron-develop

build: off

test_script:
  - node --version
  - npm --version
  - make sanity-checks
  - cmd: npm test

deploy_script:
  - cmd: .\scripts\ci\deploy-appveyor.bat

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/0becb34b32e20d389bb8
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
