# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g electron-prebuilt
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - ps: npm test
  - cmd: npm test
