version: '2'
volumes:
    influxdb:
    grafana:
    etcher_pki:
    etcher_cache:
    etcher_bash_history:
    etcher_config_electron:
    etcher_config_balena_etcher:
services:
  influxdb:
    restart: always
    build: ./etcher-pro-monitoring/influxdb
    network_mode: host
    volumes:
      - 'influxdb:/data'
  grafana:
    restart: always
    build: ./etcher-pro-monitoring/grafana
    network_mode: host
    volumes:
      - 'grafana:/data'
    environment:
      - 'GF_SERVER_HTTP_PORT=80'
      - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
      - 'GF_SESSION_PROVIDER=memory'
  collectd:
    build: ./etcher-pro-monitoring/collectd
    privileged: true
    restart: always
    network_mode: host
  beep:
    build: ./etcher-pro-monitoring/beep
    privileged: true
    restart: no
  benchmark:
    build: ./etcher-pro-monitoring/benchmark
    privileged: true
    restart: always
    network_mode: host
  etcher:
    build: .
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.balena.features.dbus: 1
    volumes:
      - 'etcher_pki:/root/.pki'
      - 'etcher_cache:/root/.cache'
      - 'etcher_bash_history:/root/.bash_history'
      - 'etcher_config_electron:/root/.config/Electron'
      - 'etcher_config_balena_etcher:/root/.config/balena-etcher'
    tmpfs:
      - /run
      - /tmp
      - /mnt
    environment:
      - 'BALENAELECTRONJS_OVERLAY_DELAY=4000'
      - 'BALENAELECTRONJS_SLEEP_BUTTON_POSITION=20,13'
      - 'BALENAELECTRONJS_WIFI_BUTTON_POSITION=114,13'
      - 'BALENAELECTRONJS_ZOOM_FACTOR=1.28'
      - 'BALENAELECTRONJS_MOUNTS_ROOT=/mnt'
      - 'BALENAELECTRONJS_CONSTRAINT_PATH=/mnt'
